CREATE TABLE BOAT(
	BID NUMBER(10) PRIMARY KEY,
	BNAME VARCHAR(20),
	COLOUR VARCHAR(20)
);

CREATE TABLE SAILOR(
	SID NUMBER(10) PRIMARY KEY,
	SNAME VARCHAR(10),
	AGE NUMBER(2),
	RATING NUMBER(2)
);

CREATE TABLE RESERVES(
	BID NUMBER(10),
	SID NUMBER(10),
	PRIMARY KEY(BID,SID),
	FOREIGN KEY(BID) REFERENCES BOAT(BID) ON DELETE CASCADE,
	FOREIGN KEY(SID) REFERENCES SAILOR(BID) ON DELETE CASCADE
);


SELECT BID 
FROM RESERVES
WHERE SID = (SELECT SID
	     FROM SAILOR
	     WHERE SNAME = "Ram");

SELECT BID
FROM RESERVES
GROUP BY BID
HAVING COUNT(BID) = (SELECT COUNT(*)
		     FROM SAILOR);

SELECT COUNT(SID)
FROM RESERVES
GROUP BY(SID);


