CREATE TABLE PART(
	PNO NUMBER(10) PRIMARY KEY,	
	PNAME VARCHAR(20),
	COLOUR VARCHAR(20)
);

CREATE TABLE SUPPLIER(
	SNO NUMBER(10) PRIMARY KEY,
	SNAME VARCHAR(20),
	ADDRESS VARCHAR(20)
);

CREATE TABLE SUPPLY(
	PNO NUMBER(10),
	SNO NUMBER(10),
	QUANTITY NUMBER(10),
	PRIMARY KEY(PNO,SNO)
	FOREIGN KEY(PNO) REFERENCES PART(PNO) ON DELETE CASCADE,
	FOREIGN KEY(SNO) REFERENCES SUPPLIER(SNO) ON DELETE CASCADsE
);

SELECT PNO 
FROM SUPPLY
WHERE SNO = (SELECT SNO 
	     FROM SUPPLIER 
	     WHERE SNAME = "Ram");

SELECT SNAME 
FROM SUPPLY
WHERE PNO = (SELECT PNO
	     FROM PART
	     WHERE PNAME = 'Bolts');


DELETE FROM PART
WHERE COLOUR = "GREEN";





