SET SERVEROUTPUT ON

BEGIN
	UPDATE EMPLOYEE
	SET SALARY = CASE
	WHEN DNO = 10 THEN SALARY+(SALARY*0.15);
	ELSE SALARY
	WHERE DNO IN (10);

	dbms_output.put_line(TO_Char(SQL%ROWCOUNT)||' rows affected.');
END;
/
