CREATE TABLE PART(
	PNO NUMBER(10) PRIMARY KEY,
	PNAME VARCHAR(10),
	COLOUR VARCHAR(10)
);

CREATE TABLE WAREHOUSE(
	WNO NUMBER(10) PRIMARY KEY,
	WNAME VARCHAR(20),
	CITY VARCHAR(10)
);

CREATE TABLE SHIPMENT(
	PNO NUMBER(10),
	WNO NUMBER(10),
	QUANTITY NUMBER(10),
	DATE1 VARCHAR(10)
	PRIMARY KEY(PNO,WNO),
	FOREIGN KEY(PNO) REFERENCES PART(PNO) ON DELETE CASCADE,
	FOREIGN KEY(WNO) REFERENCES WAREHOUSE(WNO) ON DELETE CASCADE
);

SELECT WNAME 
FROM WAREHOUSE
WHERE WNO IN (SELECT WNO
	     FROM SHIPMENT
	     WHERE PNO IN (SELECT PNO 
			  FROM PART
		 	  WHERE COLOUR = "Red"));

SELECT PNO
FROM SHIPMENT
GROUP BY(PNO)
HAVING COUNT(PNO) = (SELECT COUNT(*)
		     FROM WAREHOUSE);

SELECT WNO
FROM SHIPMENT
GROUP BY(WNO);


