CREATE TABLE BOOK(
	ISBN NUMBER(10) PRIMARY KEY,
	TITLE VARCHAR(20),
	AUTHOR VARCHAR(20),
	PUBLISHER VARCHAR(20)
);

CREATE TABLE STUDENT(
	USN NUMBER(10) PRIMARY KEY,
	NAME VARCHAR(10),
	SEM NUMBER(10),
	DEPTNO NUMBER(10)
);

CREATE TABLE BORROW(
	ISBN NUMBER(10),
	USN NUMBER(10),
	DATE1 VARCHAR(10),
	PRIMARY KEY(ISBN,USN),
	FOREIGN KEY(ISBN) REFERENCES BOOK(ISBN) ON DELETE CASCADE,
	FOREIGN KEY(USN) REFERENCES STUDENT(USN) ON DELETE CASCADE
);

SELECT NAME 
FROM STUDENT 
WHERE USN = (SELECT USN
	     FROM BORROW
	     WHERE ISBN = "123");

SELECT SNAME
FROM STUDENT
WHERE USN IN (SELECT USN 
	      FROM BORROW
	      WHERE ISBN = (SELECT ISBN
			    FROM BOOK
			    WHERE TITLE = 'Databse'));

SELECT COUNT(USN)
FROM BORROW
GROUP BY USN;
